apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: argo-rollouts
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
  - web:
      url: https://github.com/vvtelu/rollout-extension/releases/download/v2.0/extension.tar
